.TH BLAKE "1" "2012" "" ""


.SH "NAME"
blake \- Agnostic site bakery

.SH SYNOPSIS


.B blake
[
.B path/to/input
]
[
.B path/to/output
[
.B file1 file2 file3 ... 
]


.SH DESCRIPTION

Blake is a set of functions for Node.js which provides
a simple infrastructure to generate static web sites.

.SH RESOURCES AND DOCUMENTATION

See the website for documentation http://michaelnisi.github.com/blake/
